import { NavBar } from '@/components/nav-bar/NavBar';
import '../styles/main.css';
import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';

const nunitoSans = Nunito_Sans({
  weight: ['300', '600', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Where in the world? frontend-mentor challenge',
  description: 'Generated by me using create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
